@startuml
!pragma layout smetana
Title Carport_med_fladt_tag

|Kunde|
start
:gå til hjemmeside;
|Hjemmeside|
:bestil carport;
:vælg længde;
:vælg brede;
:vælg trapeztag;
:udfyld kontaktoplysninger;
:opret bruger;
|Admin|
:godkend/afvis bestilling;
:lav tilbud inkl. stykliste;
:send til kunde;
|Kunde|
:gå til hjemmeside;
|Hjemmeside|

:følge ordre;
:godkende/afivs tilbud;
|Hjemmeside|
:afslutte ordre;

@enduml